#include "engine.literary.h"

#define ENGINE_MODE_SLEEP					200

#define ENGINE_TEXT_MAX_LENGTH				64
//#define ENGINE_DATABASE_LIST_LENGTH_MAX		512 // approx. max length, no crashes (512)
#define ENGINE_DATABASE_INDEX_BLOCK_SIZE	8
#define ENGINE_COLOR_MAP_BACKGROUND			BRN
#define ENGINE_COLOR_FACING					BL
#define ENGINE_BATTLE_SIMULATION			1
#define ENGINE_EXPERIENCE_MULTIPLIER		0.25
#define ENGINE_TEST							0

#define ENGINE_RESOURCE_AMOUNT				8
#define ENGINE_CREATURE_AMOUNT				5		
#define ENGINE_BATTLE_LAST					10


#define ENGINE_SPRITE_TEMPLATE			{X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}
#define ENGINE_SPRITE_TEMP_A			{R, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, DGR, X, X, X, X, 	X, X, DGR, GR, DGR, X, X, X, 	X, X, GR, LGR, GR, X, X, X,	 X, X, X, X, X, X, X, X, 	7, 7}
#define ENGINE_SPRITE_TEMP_B			{Y, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, DGR, X, X, X, X, 	X, X, DGR, GR, DGR, X, X, X, 	X, DGR, GR, LGR, GR, DGR, X, X, 	X, DGR, GR, LGR, GR, DGR, X, X, 	X, X, GR, LGR, GR, X, X, X,		X, X, X, X, X, X, X, X, 	7, 7}
#define ENGINE_SPRITE_TEMP_C			{G, X, X, DGR, X, X, X, X, 	X, X, DGR, GR, DGR, X, X, X, 	X, DGR, DGR, GR, DGR, DGR, X, X, 	DGR, DGR, GR, LGR, GR, DGR, DGR, X, 	DGR, GR, GR, LGR, GR, GR, DGR, X, 	DGR, GR, GR, LGR, GR, GR, DGR, X, 	X, DGR, GR, LGR, GR, DGR, X, X,	 X, X, X, X, X, X, X, X, 7, 7}
#define ENGINE_SPRITE_TEMP_D			{BL, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

#define ENGINE_ANIMATION_TEST			{3, ENGINE_SPRITE_TEMP_A, ENGINE_SPRITE_TEMP_B, ENGINE_SPRITE_TEMP_C, ENGINE_SPRITE_TEMP_D}

#define ENGINE_ANM_TEST					{ENGINE_SPRITE_TEMP_A, ENGINE_SPRITE_TEMP_B, ENGINE_SPRITE_TEMP_C}

// Square
#define ENGINE_MAP_SPRITE_SQUARE_ONE	{{R, GR, GR, GR, G, 			GR, GR, GR, GR, GR, 		GR, GR, GR, GR, GR, 		GR, GR, GR, GR, GR, 		Y, GR, GR, GR, BL}, 5, 5}
#define ENGINE_MAP_SPRITE_SQUARE_TWO	{{BL, GR, GR, GR, R,			GR, GR, GR, GR, GR,			GR, GR, GR, GR, GR,			GR, GR, GR, GR, GR, 		G, GR, GR, GR, Y }, 5, 5}
#define ENGINE_MAP_SPRITE_SQUARE_THREE	{{Y, GR, GR, GR, BL,			GR, GR, GR, GR, GR, 		GR, GR, GR, GR, GR,			GR, GR, GR, GR, GR,			R, GR, GR, GR, G }, 5, 5}
#define ENGINE_MAP_SPRITE_SQUARE_FOUR	{{G, GR, GR, GR, Y,				GR, GR, GR, GR, GR, 		GR, GR, GR, GR, GR, 		GR, GR, GR, GR, GR,			BL, GR, GR, GR, R}, 5, 5}
#define ENGINE_MAP_ANIMATION_SQUARE		{ENGINE_MAP_SPRITE_SQUARE_ONE, ENGINE_MAP_SPRITE_SQUARE_TWO, ENGINE_MAP_SPRITE_SQUARE_THREE, ENGINE_MAP_SPRITE_SQUARE_FOUR}

// Defense
#define ENGINE_MAP_SPRITE_DEFENSE		{{LGR, LGR, LGR, LGR, LGR,		LGR, GR, GR, GR, LGR,		LGR, GR, DGR, GR, LGR,		X, LGR, GR, LGR, X,			X, X, LGR, X, X,}, 5, 5}

// Offense
#define ENGINE_MAP_SPRITE_OFFENSE_ONE	{X, X, GR, LGR, X, X, X, X,		X, GR, LGR, X, GR, X, X, X,		LGR, X, DGR, DGR, LGR, GR, X, X,	GR, LGR, DGR, DGR, X, LGR, X, X,	X, GR, X, LGR, GR, X, X, X,		X, X, LGR, GR, X, X, X, X,	X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_OFFENSE_TWO	{X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}
#define ENGINE_MAP_ANIMATION_OFFENSE	{ENGINE_MAP_SPRITE_OFFENSE_ONE}

// Halt
#define ENGINE_MAP_SPRITE_HALT			{X, X, DR, DR, DR, DR, X, X,		X, DR, X, X, X, X, DR, X,	DR, X, R, X, X, X, X, DR,	DR, X, X, R, X, X, X, DR,	DR, X, X, X, R, X, X, DR,	DR, X, X, X, X, R, X, DR,	X, DR, X, X, X, X, DR, X,	X, X, DR, DR, DR, DR, X, X}

// Support
#define ENGINE_MAP_SPRITE_SUPPORT		{{X, X, X, X, X, DGR, X,  		X, X, X, X, GR, X, DGR, 		X, X, X, X, LGR, GR, X,  		X, X, X, LGR, X, X, X,  		X, GR, LGR, X, X, X, GR,  		GR, DGR, GR, LGR, LGR, LGR, X,  		X, GR, X, X, X, X, GR}, 7, 7}

// Shuriken
#define ENGINE_MAP_SPRITE_SHURIKEN_ONE	{X, X, GR, LGR, X, X, X, X,		X, GR, LGR, X, GR, X, X, X,		LGR, X, DGR, DGR, LGR, GR, X, X,	GR, LGR, DGR, DGR, X, LGR, X, X,	X, GR, X, LGR, GR, X, X, X,		X, X, LGR, GR, X, X, X, X,	X, X, X, X, X, X, X, X,		X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_SHURIKEN_TWO	{X, X, X, GR, LGR, X, X, X, 	LGR, X, GR, LGR, X, X, X, X, 	GR, LGR, DGR, DGR, GR, X, X, X, 	X, GR, DGR, DGR, LGR, GR, X, X, 	X, X, LGR, GR, X, LGR, X, X, 	X, LGR, GR, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

#define ENGINE_MAP_ANIMATION_SHURIKEN	{ENGINE_MAP_SPRITE_SHURIKEN_ONE, ENGINE_MAP_SPRITE_SHURIKEN_TWO}
// Scythe
#define ENGINE_MAP_SPRITE_SCYTHE		{X, X, X, DGR, DGR, DGR, X, X,		X, DGR, DGR, LGR, LGR, DBR, X, X,		DGR, LGR, LGR, X, X, DBR, X, X,		LGR, X, X, X, DBR, X, X, X,		X, X, X, X, DBR, X, X, X,		X, X, X, DBR, X, X, X, X,	X, X, X, DBR, X, X, X, X,	X, X, X, DBR, X, X, X, X }

// Grass 
//#define ENGINE_MAP_SPRITE_PLANT			{X, X, DG, Z, X, X, X, X, 	DG, G, X, X, X, X, X, X, 	X, LG, X, X, X, X, X, X, 	BRN, BRN, BRN, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_PLANT			{{X, X, DG,	DG, G, X,	X, LG, X,	DBR, DBR, DBR}, 3, 4}
#define ENGINE_MAP_SPRITE_PLANT_WATERED	{X, X, DG, X, X, X, X, X, 	DG, G, X, X, X, X, X, X, 	X, LG, X, X, X, X, X, X, 	DBR, DBR, DBR, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

// Berry
//#define ENGINE_MAP_SPRITE_BERRY			{X, R, R, R, X, X, X, X, 	R, DR, DR, DR, R, X, X, X, 	R, DR, DR, R, R, X, X, X, 	R, DR, R, R, R, X, X, X, 	X, R, R, R, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}
#define ENGINE_MAP_SPRITE_BERRY			{{X, R, R, R, X, 	R, DR, DR, DR, R,  	R, DR, DR, R, R,  	R, DR, R, R, R, 	X, R, R, R, X}, 5, 5}

// Stone
#define ENGINE_MAP_SPRITE_STONE			{DGR, GR, X, X, X, X, X, X, 	GR, DGR, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X, 	X, X, X, X, X, X, X, X}

// Currency
#define ENGINE_MAP_SPRITE_CURRENCY		{X, X, X, DGR, DGR, X, X, X, 	X, X, DGR, PNK, PNK, DGR, X, X, 	X, DGR, PNK, PNK, PNK, PNK, DGR, X, 	DGR, GR, PNK, PNK, PNK, PNK, GR, DGR, 	DGR, DPNK, GR, GR, GR, GR, DPNK, DGR, 	X, DGR, DPNK, DPNK, DPNK, DPNK, DGR, X, 	X, X, DGR, DPNK, DPNK, DGR, X, X, 	X, X, X, DGR, DGR, X, X, X}

// Copyright
#define ENGINE_MAP_SPRITE_COPYRIGHT		{{X, X, R, R, R, R, X, X,		X, R, X, X, X, X, R, X,		R, X, X, R, R, X, X, R,		R, X, R, X, X, X, X, R,		R, X, R, X, X, X, X, R,		R, X, R, X, X, X, X, R,		R, X, X, R, R, X, X, R,		X, R, X, X, X, X, R, X,		X, X, R, R, R, R, X, X}, 8, 9}

// Dario
#define ENGINE_MAP_SPRITE_DERRIS		{{X, X, X, DBR, DBR, DBR, X, X,		X, X, DBR, DBR, DBR, DBR, DBR, X,	X, DBR, DBR, B, LBR, B, X, X,	X, DBR, DBR, LBR, LBR, LBR, X, X,	X, X, LBR, LBR, B, LBR, X, LBR,		LBR, LBR, LBL, LBR, LBR, LBL, LBR, LBR,		LBR, LBR, LBL, LBL, LBL, LBL, LBR, X,	X, X, LBL, LBL, LBL, LBL, X, X,		X, LBL, LBL, X, LBL, LBL, LBL, X,		DG, LBL, LBL, X, X, LBL, LBL, DG,	G, G, G, X, X, G, G, G }, 8, 11}

// Placeholder
#define ENGINE_MAP_SPRITE_DUMMY			{{X, GR, GR, X,		GR, DGR, DGR, GR,	GR, DGR, DGR, GR,	X, GR, GR, X}, 4, 4}

// Mario {{X, X, X, LBL, LBL, LBL, LBL, LBL, X, X, X, X,		X, X, LBL, LBL, LBL, LBL, LBL, LBL, LBL, LBL, LBL, X,		X, X, DBR, DBR, DBR, LBR, LBR, B, LBR, X, X, X,		X, DBR, LBR, DBR, DBR, LBR, LBR, B, LBR, LBR, LBR, X,	X, DBR, LBR, DBR, DBR, LBR, LBR, LBR, DBR, LBR, LBR, LBR,	X, DBR, DBR, LBR, LBR, LBR, LBR, DBR, DBR, DBR, DBR, X,		X, X, X, LBR, LBR, LBR, LBR, LBR, LBR, LBR, X, X,	X, X, LBL, LBL, BL, LBL, LBL, LBL, X, X, X, X,	X, LBL, LBL, LBL, BL, LBL, LBL, BL, LBL, LBL, LBL, X,	LBL, LBL, LBL, LBL, BL, BL, BL, BL, LBL, LBL, LBL, LBL,		LBR, LBR, LBL, BL, Y, BL, BL, Y, BL, LBL, LBR, LBR,		LBR, LBR, LBR, BL, BL, BL, BL, BL, BL, LBR, LBR, LBR,	LBR, LBR, BL, BL, BL, BL, BL, BL, BL, BL, LBR, LBR,		X, X, BL, BL, BL, X, X, BL, BL, BL, X, X,	X, DBR, DBR, DBR, X, X, X, X, DBR, DBR, DBR, X,		DBR, DBR, DBR, DBR, X, X, X, X, DBR, DBR, DBR, DBR}, 12, 16}


#define ENGINE_POLYGON_SPEAR			{{{0.5, -1.25, 0.5}, {0.5, 4.0, 0.5}, {0.5, 6.0, 0.5}, {0.5, 8.0, 0.5}, {1.0, 1.0, 0.0}, {0.0, 1.0, 0.0}, {0.0, 1.0, 1.0}, {1.0, 1.0, 1.0}, {1.0, 3.0, 0.0}, {1.0, 3.0, 1.0}, {0.0, 3.0, 0.0}, {0.0, 3.0, 1.0}}, 10.0, 10.0, 10.0, {}}
#define ENGINE_POLYGON_CUBE				{{{1.0, 1.0, 0.0}, {0.0, 1.0, 0.0}, {1.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {1.0, 1.0, 1.0}, {0.0, 1.0, 1.0}, {1.0, 0.0, 1.0}, {0.0, 0.0, 1.0}}, 40.0, 40.0, 40.0, {{0, 1}, {0, 2}, {1, 3}, {2, 3}, {4, 5}, {4, 6}, {5, 7}, {6, 7}, {0, 4}, {1, 5}, {2, 6}, {3, 7}}}
#define ENGINE_POLYGON_HANDLE			{{}, 10.0, 50.0, 5.0, {}}
// Limbs											(health, offense, defense, energy)

#define ENGINE_BIONIC					{0.0001, "Bionic",		0, 1, 0, 1}
#define ENGINE_BIONIC_HEAD				{0.00011, "Head",		8, 1, 0, 1}
#define ENGINE_BIONIC_EYE				{0.000111, "Eye",		3, 0, 0}
#define ENGINE_BIONIC_NOSE				{0.000112, "Nose",		3, 0, 0}
#define ENGINE_BIONIC_MOUTH				{0.000113, "Mouth",		3, 1, 0, 1}
#define ENGINE_BIONIC_LIP				{0.0001131, "Lip",		1, 1, 1, 0}
#define ENGINE_BIONIC_TONGUE			{0.0001132, "Tongue",	1, 1, 0, 1}
#define ENGINE_BIONIC_EAR				{0.000114, "Ear",		3, 0, 0, 1}
#define ENGINE_BIONIC_ARM				{0.00012, "Arm",		6, 2, 0, 2}
#define ENGINE_BIONIC_ELBOW				{0.000121, "Elbow",		4, 1, 0}
#define ENGINE_BIONIC_HAND				{0.000122, "Hand",		3, 1, 0, 1}
#define ENGINE_BIONIC_FINGER			{0.0001211, "Finger",	2, 0, 0, 1}
#define ENGINE_BIONIC_LEG				{0.00013, "Leg",		6, 2, 0}
#define ENGINE_BIONIC_KNEE				{0.000131, "Knee",		4, 1, 0}
#define ENGINE_BIONIC_FOOT				{0.000132, "Foot",		3, 1, 0, 1}
#define ENGINE_BIONIC_TOE				{0.0001311, "Toe",		2, 0, 0}

#define ENGINE_CARCASS					{0.0002, "Carcass",		0, 1, 0, 1}
#define ENGINE_CARCASS_TISSUE			{0.00021, "Tissue",		2, 1, 0}
#define ENGINE_CARCASS_CELL				{0.000211, "Cell",		1, 1, 0, 1}
#define ENGINE_CARCASS_HAIR				{0.00022, "Hair",		1, 0, 1, 1}

#define ENGINE_BOTANY					{0.0003, "Botany",		0, 1, 0, 1}
#define ENGINE_BOTANY_SPROUT			{0.00031, "Sprout",		6, 0, 0}
#define ENGINE_BOTANY_BRANCH			{0.000311, "Branch",	4, 1, 0}
#define ENGINE_BOTANY_BLOOM				{0.0003111, "Bloom",	2, 0, 0, 2}

#define ENGINE_MIRAGE					{0.0004, "Mirage",		0, 1, 0, 1}
#define ENGINE_MIRAGE_WING				{0.00041, "Wing",		4, 0, 0, 2}
#define ENGINE_MIRAGE_TAIL				{0.00042, "Tail",		3, 1, 1, 1}

#define ENGINE_PART_POOL				{ENGINE_CARCASS_CELL, ENGINE_CARCASS_TISSUE, ENGINE_BIONIC_ARM, ENGINE_BIONIC_HAND, ENGINE_BIONIC_FINGER, ENGINE_BOTANY_BRANCH, ENGINE_BOTANY_BLOOM, ENGINE_BIONIC_LEG, ENGINE_BIONIC_KNEE, ENGINE_BIONIC_FOOT, ENGINE_BIONIC_TOE, ENGINE_MIRAGE_WING}
#define ENGINE_PART_POOL_ALL			{ENGINE_BIONIC_HEAD, ENGINE_BIONIC_EYE, ENGINE_BIONIC_NOSE, ENGINE_BIONIC_MOUTH, ENGINE_BIONIC_EAR, ENGINE_BIONIC_LIP, ENGINE_BIONIC_TONGUE, ENGINE_BIONIC_ARM, ENGINE_BIONIC_ELBOW, ENGINE_BIONIC_HAND, ENGINE_BIONIC_FINGER, ENGINE_BIONIC_LEG, ENGINE_BIONIC_KNEE, ENGINE_BIONIC_FOOT, ENGINE_BIONIC_TOE, ENGINE_CARCASS_TISSUE, ENGINE_CARCASS_CELL, ENGINE_CARCASS_HAIR, ENGINE_BOTANY_SPROUT, ENGINE_BOTANY_BRANCH, ENGINE_BOTANY_BLOOM, ENGINE_MIRAGE_WING, ENGINE_MIRAGE_TAIL}

#define ENGINE_TYPE_CREATURE			1010
#define ENGINE_TYPE_CREATURE_FRIENDLY	1011
#define ENGINE_TYPE_CREATURE_HOSTILE	1012
#define ENGINE_TYPE_CREATURE_NEUTRAL	1013

#define ENGINE_TYPE_RESOURCE			1020
#define ENGINE_TYPE_RESOURCE_PLANT		1021
#define ENGINE_TYPE_RESOURCE_BERRY		1022
#define ENGINE_TYPE_RESOURCE_STONE		1023
#define ENGINE_TYPE_RESOURCE_CURRENCY	1024

#define ENGINE_TYPE_TILE				1030
#define ENGINE_TYPE_TILE_DESOLATE		1031
#define ENGINE_TYPE_TILE_MEADOW			1032
#define ENGINE_TYPE_TILE_SWAMP			1033
#define ENGINE_TYPE_TILE_WATER			1034
#define ENGINE_TYPE_TILE_TEST			1039
//#define ENGINE_TYPE_EFFECT				1040

#define ENGINE_TYPE_DUS_SQUARE			1050
#define ENGINE_TYPE_DUS_OFFENSE			1051
#define ENGINE_TYPE_DUS_DEFENSE			1052
#define ENGINE_TYPE_DUS_HALT			1053
#define ENGINE_TYPE_DUS_SUPPORT			1054

#define ENGINE_TYPE_EFFECT				1060
#define ENGINE_TYPE_EFFECT_FROZEN		1061
#define ENGINE_TYPE_EFFECT_BURNING		1062
#define ENGINE_TYPE_EFFECT_BLEEDING		1063
#define ENGINE_TYPE_EFFECT_VAMPIRIC		1064

#define ENGINE_COOLDOWN_HEAL			15
#define ENGINE_COOLDOWN_BERRY			10

// Effects

#define ENGINE_EFFECT_NONE				{ENGINE_TYPE_EFFECT, 0}
#define ENGINE_EFFECT_FROST				{ENGINE_TYPE_EFFECT_FROZEN, 3} // No energy [replenish], no offense
#define ENGINE_EFFECT_BURN				{ENGINE_TYPE_EFFECT_BURNING, 2} // Damage over loop
#define ENGINE_EFFECT_BLEED				{ENGINE_TYPE_EFFECT_BLEEDING, 3}
#define ENGINE_EFFECT_DRAIN				{ENGINE_TYPE_EFFECT_VAMPIRIC, 2}

// Abilities

#define ENGINE_ABILITY_FROST			{"Frost", 5, 1, ENGINE_EFFECT_FROST, 0.1}
#define ENGINE_ABILITY_FLAME			{"Flame", 6, 2, ENGINE_EFFECT_BURN, 0.5}
#define ENGINE_ABILITY_SHIELD			{"Shield", 12, 3, ENGINE_EFFECT_NONE, 8.0}
#define ENGINE_ABILITY_CUT				{"Cut", 20, 3, ENGINE_EFFECT_BLEED, 0.25}
#define ENGINE_ABILITY_DRAIN			{"Drain", 25, 4, ENGINE_EFFECT_DRAIN, 1.0}

// Dus
#define ENGINE_DUS_SQUARE				{0.0000001, ENGINE_TYPE_DUS_SQUARE, "Square"}
#define ENGINE_DUS_DEFENSE				{0.0000002, ENGINE_TYPE_DUS_DEFENSE, "Defense", 2}
#define ENGINE_DUS_OFFENSE				{0.0000003, ENGINE_TYPE_DUS_OFFENSE, "Offense", 1}
#define ENGINE_DUS_HALT					{0.0000004, ENGINE_TYPE_DUS_HALT, "Halt", 2}
#define ENGINE_DUS_SUPPORT				{0.0000005, ENGINE_TYPE_DUS_SUPPORT, "Support", 1}
#define ENGINE_DUS_TEST					{0.00000124, -1, "Test", 0}
#define ENGINE_DUS_MOVE					{0.00000123, -1, "Move", 1}


#define ENGINE_D						{0.0000001, "D", ENGINE_DUS_SQUARE, ENGINE_TYPE_CREATURE, ENGINE_MAP_ANIMATION_SQUARE,			2, 5, 5}
#define ENGINE_CREATURE_DEFENSE			{0.0000002, "Defense", ENGINE_DUS_DEFENSE, ENGINE_TYPE_CREATURE, {ENGINE_MAP_SPRITE_DEFENSE},		2, 5, 5}
#define ENGINE_CREATURE_REAPER			{0.0000003, "Reap", ENGINE_DUS_OFFENSE, ENGINE_TYPE_CREATURE, {ENGINE_MAP_SPRITE_SCYTHE},		2, 6, 8}
#define ENGINE_CREATURE_OFFENSE			{0.0000004, "Offense", ENGINE_DUS_OFFENSE, ENGINE_TYPE_CREATURE, ENGINE_MAP_ANIMATION_SHURIKEN,	2, 6, 6}
#define ENGINE_CREATURE_HALT			{0.0000005, "Halt", ENGINE_DUS_HALT, ENGINE_TYPE_CREATURE, {ENGINE_MAP_SPRITE_HALT},	2, 8, 8}
#define ENGINE_CREATURE_SUPPORT			{0.0000006, "Support", ENGINE_DUS_SUPPORT, ENGINE_TYPE_CREATURE, {ENGINE_MAP_SPRITE_SUPPORT}, 2, 7, 7}
#define ENGINE_CREATURE_CHECKER			{0.0000007, "Checker", ENGINE_DUS_SUPPORT, ENGINE_TYPE_CREATURE, {ENGINE_MAP_SPRITE_COPYRIGHT}, 1, 8, 9}
#define ENGINE_CREATURE_DERRIS			{0.0000008, "Derris", ENGINE_DUS_SUPPORT, ENGINE_TYPE_CREATURE, {ENGINE_MAP_SPRITE_DERRIS}, 2, 8, 11}

#define ENGINE_RESOURCE_PLANT			{0.0000101, "Plant", ENGINE_DUS_DEFENSE, ENGINE_TYPE_RESOURCE_PLANT, {ENGINE_MAP_SPRITE_PLANT},		2, 3, 4, 0}
#define ENGINE_RESOURCE_BERRY			{0.0000102, "Berry", ENGINE_DUS_OFFENSE, ENGINE_TYPE_RESOURCE_BERRY, {ENGINE_MAP_SPRITE_BERRY},		1, 5, 5, 0}
#define ENGINE_RESOURCE_STONE			{0.0000103, "Stone", ENGINE_DUS_DEFENSE, ENGINE_TYPE_RESOURCE_STONE, {ENGINE_MAP_SPRITE_STONE},		2, 2, 2, 0}
#define ENGINE_RESOURCE_CURRENCY		{0.0000, "Currency", ENGINE_DUS_DEFENSE, ENGINE_TYPE_RESOURCE_CURRENCY,{ENGINE_MAP_SPRITE_CURRENCY},		1, 8, 8, 0}
#define ENGINE_DRAW						101
#define ENGINE_SPRITEGRAPH	{}

